zuul:
  ignoredServices: '*'
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders:

    account-service:
      path: /account/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders:

ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 20000

server:
  port: 4000