security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ACCOUNT_SERVICE_PASSWORD
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/account
    username: POSTGRES_USER
    password: POSTGRES_PASSWORD
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /account
  port: 6000

account:
  verification:
    expiration: 120
  path:
    confirm-registration: /account/public/registration-confirm
    forgot-password: /account/public/reset-password
