server:
  servlet:
    context-path: /uaa
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://auth-db/oauth2
    username: POSTGRES_USER
    password: POSTGRES_PASSWORD
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none