spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    username: examplevn@gmail.com
    password: vnext@2019
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false